### ISSUE TITLE
Pokemon Silver hangs if you don't use cgb_bios.bin

### ISSUE THREAD

**Issue by lambertjamesd** [lambertjamesd/gb64#12]

**Comment by bryc** [comment]
There might be many games that need BIOS to boot. Just going alphabetically, these hang too:

## DMG
- Adventure Island II - Aliens in Paradise (USA, Europe)
- Adventures of Lolo (Europe) (SGB Enhanced)
- Aerostar (USA, Europe)

## CGB
- Aladdin (USA)
- Balloon Fight GB (Japan) (NP,SGB Enhanced)
- Batman Beyond - Return of the Joker (USA)
