### ISSUE TITLE
Sound bugs

### ISSUE THREAD

**Issue by bryc** [lambertjamesd/gb64#13]
There are some issues regarding sound. 

### Frequency/pitch is sometimes incorrect

- **Adventure Island (USA, Europe)**  - The sound is basically cursed in this game.
- **A-mazing Tater (USA)** - Bass notes in music is out of pitch.

### Related to Pitch-sweep
- **Atomic Punk (USA).gb** - Game makes heavy use of pitch sweep effect, which does not work properly.
- **Super Mario Land (World) (Rev A).gb** - Mario's jump is missing the pitch sweep effect.
- **Alfred Chicken (USA).gb** - Wave channel lingers on when game is paused. Pitch sweep also missing when jumping/bouncing.

### Other sound-related issues
- **Adventures of Lolo (Europe) (SGB Enhanced).gb** - When resetting level (with B), the 'game over' jingle doesn't fully play.
- **Alleyway (World).gb** - Hanging frequency sound FX when ball hits the wall.
- **Amazing Penguin (USA, Europe).gb** - Hanging frequencies at end of title screen jingle (e.g. noise channel doesn't mute when it should).
- **Another Bible (Japan).gb** - errors in playback of title screen sequence - a gap of silence between loops that shouldn't be there.
- **Asmik-kun World 2 (Japan).gb** - bassline of in-game music is a constant sound, not changing properly as it should.

**Comment by lambertjamesd** [comment]
Fixed the sound issues
