### ISSUE TITLE
Can resolution be raised to 640x480, for clean upscaling?

### ISSUE THREAD

**Issue by HeyItsLollie** [lambertjamesd/gb64#16]
I posted this on the Everdrive64/Krikzz forums, but I wasn't sure if you check the forums.

Would it be possible to run the emulator at 640x480?
This would allow for cleaner upscaling on N64, potentially up to 3x scale. (160x144 -> 480x432)

**Comment by lambertjamesd** [comment]
I'll look into it as an option.

**Comment by lambertjamesd** [comment]
I updated the emulator to run at a higher resolution. The changes will be out with the next release.

**Comment by HeyItsLollie** [comment]
Wicked, thank you!
