### ISSUE TITLE
Force ram settings via rom header (or make standalone emulator, for integration with Everdrive OS)

### ISSUE THREAD

**Issue by HeyItsLollie** [lambertjamesd/gb64#17]
Passing this message along from KRIKzz at the Everdrive64/KRIKzz forums, in case this hasn't been seen:
https://krikzz.com/forum/index.php?topic=10049.msg77023#msg77023
> Nice work! I would suggest if possible using ram settings forcing via rom header, it supported in last OS. You just need to set rom ID to "ED" and then you can specify save type in byte at offset 0x3F. Values is the same as for save_db. 0x30 for sram, 0x50 for flashram.
As alternate method can be used rom ID from some known game which used flash or sram. Manual save_db editing for each game isn't handy way (:
Or may be even make it stand alone for make possible integration to the cart menu, just like nes emu

**Comment by lambertjamesd** [comment]
Done
