### ISSUE TITLE
Homebrew game crashes emulator

### ISSUE THREAD

**Issue by TheRetroRoomRoo** [lambertjamesd/gb64#24]
First off, I appreciate your hard work in making this in the first place, very very cool. I am having a problem with it even launching the rom.. it fails nearly immediately. To be fair, I have only tried it on one emulator, but no matter what I did, I couldnt get it to work. I have GB and GBC versions of my games. I tried a few different variations of the bios and settings, it just would never launch
I also have a DMG version of this game, so even if color doesnt work, my audience appreciates a regular gameboy game

I get an "Unknown memory action" error. I sent the rom over to you on reddit in a message. Curious if its something wrong with my rom or what is going on. I am using project64 emulator.

**Comment by lambertjamesd** [comment]
What ROM are you using so I can reproduce the problem?

**Comment by TheRetroRoomRoo** [comment]
> What ROM are you using so I can reproduce the problem?

I am using a few homebrew games that I built using GBStudio. One example can be found here https://theretroroomroo.itch.io/questarrest

I would love to be able to use this for releasing N64 games in the future. Good work for sure and thank you for this!

**Comment by TheRetroRoomRoo** [comment]
Upon further inspection it doesn't work with emulators but it works on hardware! I ordered a retroblaster and tested. All good to go! Thanks again for making such an awesome tool!
