### ISSUE TITLE
Some DMG games use bad CGB colors

### ISSUE THREAD

**Issue by bryc** [lambertjamesd/gb64#4]
When using the online ROM builder, I loaded the BIOS files first before loading any games. However some of the DMG games are detected (possibly incorrectly) to use the CGB bios.

This seems to mess up the color palettes in some games, and many of these predate CGB so don't have any real support for it. Here are some screenshots from cen64:

## Donkey Kong Land
![image](https://user-images.githubusercontent.com/1408749/87365706-e8a81900-c544-11ea-90d8-f925931c1818.png)

## Kirby's Dream Land
![image](https://user-images.githubusercontent.com/1408749/87365595-a2eb5080-c544-11ea-82c1-3fc5d0a984b9.png)

## Adventure Island
![image](https://user-images.githubusercontent.com/1408749/87360320-dffd1600-c537-11ea-83bb-4bc7155f5284.png)

Also I tried building this game without specifying BIOS - it doesn't display any graphics.
## Adventure Island II
![image](https://user-images.githubusercontent.com/1408749/87360349-ee4b3200-c537-11ea-90c5-bafa1f7ee441.png)
## Another Bible (J)
![image](https://user-images.githubusercontent.com/1408749/87360368-fa36f400-c537-11ea-9bd1-14a091bd9cba.png)
## Battletoads in Ragnarok's World
![image](https://user-images.githubusercontent.com/1408749/87360408-0e7af100-c538-11ea-8007-38f15b47fde1.png)

**Comment by lambertjamesd** [comment]
I found the issue and it has been fixed
