### ISSUE TITLE
Amazing Tater - pause menu glitch

### ISSUE THREAD

**Issue by bryc** [lambertjamesd/gb64#5]
Amazing Tater is a simple puzzle game (Sokoban) - pressing A should bring up a pause menu with Retry / Hint.

gb64:
![image](https://user-images.githubusercontent.com/1408749/87362288-3b310780-c53c-11ea-8af2-2abcc6ea90af.png)

bgb:
![image](https://user-images.githubusercontent.com/1408749/87362561-fb1e5480-c53c-11ea-8b34-3dd0a1e0af7d.png)

**Comment by lambertjamesd** [comment]
Fixed
