### ISSUE TITLE
Games that crash/freeze immediately after BIOS

### ISSUE THREAD

**Issue by bryc** [lambertjamesd/gb64#6]
## DMG
- Adventures of Star Saver, The (USA, Europe)
- Block Kuzushi GB (Japan) (SGB Enhanced)
- Bonk's Adventure (USA)
- Boomer's Adventure in ASMIK World (USA)
- Fighting Simulator 2 in 1 (USA, Europe)
- Motocross Maniacs (USA)
- Nettou Real Bout Garou Densetsu Special (Japan) (SGB Enhanced)
- Nettou The King of Fighters '96 (Japan) (SGB Enhanced)
- Penguin Wars (USA)
- Picross 2 (Japan) (SGB Enhanced)
- Popeye 2 (Europe)
- Q Billion (USA)
- Serpent (USA)
- Shikinjou (Japan)
- Wario Land - Super Mario Land 3 (World)  (Error Screen: https://i.imgur.com/ZdyL063.png)

## CGB
- Aladdin (USA)
- Donald Duck - Goin' Quackers (USA) (En,Fr,De,Es,It)
- Dragon's Lair (USA, Europe) (En,Ja,Fr,De,Es,Zh)
- Game & Watch Gallery 2 (USA, Europe) (SGB Enhanced)  (Immediate Thread Fault Error)
- Game & Watch Gallery 3 (USA, Europe) (SGB Enhanced)  (Immediate Thread Fault Error)
- Jungle Book, The - Mowgli's Wild Adventure (USA) (En,Fr,De,Es,It)
- Kirby - Tilt 'n' Tumble (USA) (`BAD MBC - 8D42` - Uses gyro)
- Konami GB Collection Vol.3 (Europe)
- Lufia - The Legend Returns (USA)
- Metal Walker (USA)  (Immediate Thread Fault Error)
- Pac-Man - Special Color Edition (USA) (SGB Enhanced)
- Pokemon - Crystal Version (USA, Europe) (Rev A)
- Pokemon Pinball (USA) (SGB Enhanced)  (Immediate Thread Fault Error)
- Robopon - Sun Version (USA) (SGB Enhanced)  (Error: `TODO MBC FE`)
- Toki Tori (USA, Europe) (En,Ja,Fr,De,Es)   (Immediate Thread Fault Error)
- Tomb Raider - Curse of the Sword (USA, Europe)  (black screen)
- Tomb Raider (USA, Europe) (En,Fr,De,Es,It) (black screen)
- Turok 3 - Shadow of Oblivion (USA, Europe) (En,Fr,De,Es) 

## Glitched / Broken games -  Beyond Bios
- Alley Way
- Mercenary Force (USA, Europe)
- Speedy Gonzales (USA, Europe)
- Cannon Fodder (USA) (En,Fr,De,Es,It)  - blue screen hangs a lot
- Frogger 2 (USA) - graphical glitches
- Lion King, The - Simba's Mighty Adventure (USA) - graphical and sound corruption
- Marble Madness (USA, Europe) - (sound is horrible - not sure if normal)
- Heroes of Might and Magic (USA) (En,Fr,De)  (doesn't crash, but flashing colors, missing graphics - unplayable)
- Heroes of Might and Magic II (USA) (En,Fr,De)  (doesn't crash, but flashing colors, missing graphics - unplayable)
- Hunter X Hunter - Kindan no Hihou (Japan)   (doesn't crash, but missing graphics - unplayable)
- Mickey's Speedway USA (USA) (En,Fr,De,Es)
- Q-bert (USA)
- Warlocked (USA) (crashes after the intro credits)
- Woody Woodpecker Racing (Europe) (graphic glitches during intro)

**Comment by lambertjamesd** [comment]
Thanks for finding some bugs. I have fixed a few already and will be working through them all.

**Comment by lambertjamesd** [comment]
Fixed crash after boot
- Adventures of Star Saver, The (USA, Europe)
- Block Kuzushi GB (Japan) (SGB Enhanced)
- Bonk's Adventure (USA)
- Boomer's Adventure in ASMIK World (USA)
- Fighting Simulator 2 in 1 (USA, Europe)
- Motocross Maniacs (USA)

Couldn't quickly find rom

- Nettou Real Bout Garou Densetsu Special (Japan) (SGB Enhanced)
- Nettou The King of Fighters '96 (Japan) (SGB Enhanced)

**Comment by lambertjamesd** [comment]
I didn't check any of the Japanese games since I couldn't quickly find the roms.
I created a separate issue for unsupported MBCs

**Comment by lambertjamesd** [comment]
I fixed most of the problems. The few issues I haven't reached yet I moved to separate issues to better track individual problems

**Comment by bryc** [comment]
amazing work - i will rebuild and see if i can find any further serious bugs
